<?php
/**
 * Created by PhpStorm.
 * User: lucius
 * Date: 22.08.16
 * Time: 19:01
 */

namespace Concrete\Package\BasicTablePackage\Src\FieldTypes;


use Concrete\Core\Device\DeviceInterface;

class DirectEditAssociatedEntityMultipleField extends DropdownMultilinkField implements DirectEditInterface
{

    public function getFormView($form){
        //begin with some html stuff to wrap it

        //foreach value, create a direct edit field

        //add add button

        //close html stuff

        //return the html stuff
    }

    public function validatePost($value)
    {
        //get the existing values


        //compare with the sent, update if necessary

        //persist them

        //give to parent

        return parent::validatePost($value); // TODO: Change the autogenerated stub
    }

}