<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-07-07T16:38:57+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'misc' => array(
        'latest_version' => '5.7.5.8',
        'do_page_reindex_check' => false,
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'cache' => array(
        'doctrine_dev_mode' => true,
    ),
);
