<?php
namespace Concrete\Package\BasicTablePackage\Src\BlockOptions;

use Concrete\Package\BasicTablePackage\Src\BlockOptions\TableBlockOption;
use Concrete\Package\BasicTablePackage\Src\EntityGetterSetter;
use Doctrine\ORM\Mapping\Table;
use Concrete\Package\BasicTablePackage\Src\Group as Group;
use Doctrine\Common\Collections\ArrayCollection as ArrayCollection;

/*because of the hack with @DiscriminatorEntry Annotation, all Doctrine Annotations need to be
properly imported*/
use Doctrine\ORM\PersistentCollection;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Concrete\Package\BasicTablePackage\Src\DiscriminatorEntry\DiscriminatorEntry;

/**
 * Class CanEditOption
 * Test Option to Link to another entity.
 * TODO add functionality, that users which are not in this group get false on  a funciton checkCondition
 * @IgnoreAnnotation("package")\n*  Concrete\Package\BasicTablePackage\Src\BlockOptions
 * @Entity
 */
class CanEditOption extends TableBlockOption{
    use EntityGetterSetter;
    protected $possibleValues = array(
        "test" => 1,
        "test2" => 1,
    );



    /**
     * @var string
     * @Column(type="string")
     */
    protected $optionType =__CLASS__;

    /**
     * @var ArrayCollection of Group
     * @ManyToMany(targetEntity="Concrete\Package\BasicTablePackage\Src\Group")
     * @JoinTable(name="caneditoptions_groups",
     *      joinColumns={@JoinColumn(name="tableblockoption_id", referencedColumnName="id", onDelete = "CASCADE")},
     *      inverseJoinColumns={@JoinColumn(name="group_id", referencedColumnName="gID", onDelete = "CASCADE")}
     *      )
     */
    protected $Groups;

    public function __construct()
    {
        $this->Groups = new ArrayCollection();
        $this->optionType == __CLASS__;
        $this->setDefaultFieldTypes();
    }



/*
    public function setOwnFieldType($bid){
        $this->fieldType= new DropdownMultilinkField("testmultilink", "Gruppen", "testmultilink");
        $this->fieldType->setLinkTable("Groups");
        $this->fieldType->setShowColumn("gName");
        $this->fieldType->setIdField("gID");
        $this->fieldType->setNtoMTable('btBasicTableOption2Group');
        $this->fieldType->setLinkFieldSelf('optionID');
        $this->fieldType->setLinkFieldExt('groupID');
        $this->fieldType->setIdFieldSelf('id');
        $this->fieldType->setIdFieldExt('gID');
        $this->fieldType->setRowId($_SESSION['blockoptions'.$this->bID."rowid"]);

    }
*/
    public function getLabel(){
        return t('Which groups can edit entries?');
    }

    public function getFieldType(){
        if($this->fieldTypes['optionValue']==null){
            $this->setDefaultFieldTypes();
        }
        if($this->optionName != null){
            $this->fieldTypes['Groups']->setLabel($this->optionName);
            $this->fieldTypes['Groups']->setPostName(str_replace(" ", "", $this->optionName));
        }
        return $this->fieldTypes['Groups'];

    }
    /*
    public function getFormView($form)
    {
        return parent::getFormView($form); // TODO: Change the autogenerated stub
    }
*/
    public function getValue(){
        if($this->Groups instanceof PersistentCollection){
            $this->Groups = new ArrayCollection($this->Groups->toArray());
        }
        return $this->Groups;
    }

    public function setValue($Groups){
        if($Groups instanceof PersistentCollection){
            $Groups = new ArrayCollection($Groups->toArray());
        }
        $this->Groups = $Groups;
    }


}