<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-11-05T20:39:13+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      log.queries.clear_on_reload
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'locale' => 'en_US',
    'site' => 'newgryfipage',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1444841265,
        'latest_version' => '5.7.3.1',
        'seen_introduction' => true,
        'do_page_reindex_check' => false,
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => true,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => true,
    ),
    'permissions' => array(
        'model' => 'normal',
    ),
    'log' => array(
        'errors' => 1,
        'emails' => 1,
        'queries' => array(
            'log' => 1,
            'clear_on_reload' => 0,
        ),
    ),
);
