<?php
/**
 * Created by PhpStorm.
 * User: lucius
 * Date: 21.12.15
 * Time: 14:53
 */

namespace Concrete\Package\BaclucPersonPackage\Src;
use Concrete\Package\BasicTablePackage\Src\EntityGetterSetter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Concrete\Package\BasicTablePackage\Src\FieldTypes\DateField;
use Concrete\Package\BasicTablePackage\Src\BaseEntity;

/*because of the hack with @DiscriminatorEntry Annotation, all Doctrine Annotations need to be
properly imported*/
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Concrete\Package\BasicTablePackage\Src\DiscriminatorEntry\DiscriminatorEntry;
use Doctrine\ORM\Mapping\Table;


/**
 * Class Address
 * package Concrete\Package\BaclucPersonPackage\Src
 * @Entity
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorEntry( value = "Concrete\Package\BaclucPersonPackage\Src\Address" )
 * @Table(name="bacluc_address")
 */
class Address extends BaseEntity implements  AddressInterface
{
    use EntityGetterSetter;
    /**
     * @var int
     * @Id @Column(type="integer")
     * @GEneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @Column(type="string")
     */
    protected $type;


    /**
     * @Column(type="string")
     */
    protected $organisation;


    /**
     * @Column(type="string", length =65535)
     */
    protected $info;





    public function __construct(){
        parent::__construct();
        if($this->People == null){
            $this->People = new ArrayCollection();
        }

    }

    public function setDefaultFieldTypes()
    {
        parent::setDefaultFieldTypes(); // TODO: Change the autogenerated stub
    }


    public static function getDefaultGetDisplayStringFunction(){
        $function = function(Address $item){

            $returnString ="";
            if(strlen($item->type)>0){
                $returnString.=$item->type." ";
            }
            if(strlen($item->organisation!=null)>0){
                $returnString.=$item->organisation." ";
            }
            if(strlen($item->info!=null)){
                $returnString.=$item->info;
            }
            return $returnString;
        };
        return $function;
    }

    public static function getFieldTypeClass()
    {
        // TODO: Implement getFieldTypeClass() method.
        return "Concrete\\Package\\BasicTablePackage\\Src\\FieldTypes\\AddressField\\AddressField";
    }


}