<?php
/**
 * Created by PhpStorm.
 * User: lucius
 * Date: 21.12.15
 * Time: 14:53
 */

namespace Concrete\Package\BaclucPersonPackage\Src;
use Concrete\Package\BasicTablePackage\Src\EntityGetterSetter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Concrete\Package\BasicTablePackage\Src\FieldTypes\DateField;
use Concrete\Package\BasicTablePackage\Src\Entity;


/**
 * Class Address
 * @package Concrete\Package\BaclucPersonPackage\Src
 * @Entity
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="discr", type="string")
 * @Table(name="bacluc_address")
 */
class Address extends Entity
{
    use EntityGetterSetter;
    /**
     * @var int
     * @Id @Column(type="integer")
     * @GEneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @Column(type="string")
     */
    protected $type;


    /**
     * @Column(type="string")
     */
    protected $organisation;


    /**
     * @Column(type="string", length =65535)
     */
    protected $info;





    public function __construct(){
        parent::__construct();
        if($this->People == null){
            $this->People = new ArrayCollection();
        }

    }

    public function setDefaultFieldTypes()
    {
        parent::setDefaultFieldTypes(); // TODO: Change the autogenerated stub
    }





}