<?php
/**
 * Created by PhpStorm.
 * User: lucius
 * Date: 21.12.15
 * Time: 14:53
 */

namespace Concrete\Package\BaclucPersonPackage\Src;
use Concrete\Package\BasicTablePackage\Src\EntityGetterSetter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Concrete\Package\BasicTablePackage\Src\FieldTypes\DateField;
use Concrete\Package\BasicTablePackage\Src\Entity;


/**
 * Class EmailAddress
 * @package Concrete\Package\BaclucPersonPackage\Src
 * @Entity
 * @Table(name="bacluc_email_address")
 */
class EmailAddress extends Address
{
    use EntityGetterSetter;
    /**
     * @var int
     * @Id @Column(type="integer")
     * @GEneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @var string
     * @Column(type="string")
     */
    protected $email;







    public function __construct(){
        parent::__construct();
        if($this->People == null){
            $this->People = new ArrayCollection();
        }

    }

    public function setDefaultFieldTypes()
    {
        parent::setDefaultFieldTypes(); // TODO: Change the autogenerated stub
    }

    public static function getDefaultGetDisplayStringFunction(){
        $function = function(EmailAddress $item){

            $returnString ="";
            if(strlen($item->email!=null)){
                $returnString.=$item->email;
            }
            return $returnString;
        };
        return $function;
    }





}