<?php
/**
 * Created by PhpStorm.
 * User: lucius
 * Date: 21.12.15
 * Time: 14:53
 */

namespace Concrete\Package\BaclucPersonPackage\Src;
use Concrete\Package\BasicTablePackage\Src\EntityGetterSetter;
use Concrete\Package\BasicTablePackage\Src\FieldTypes\EmailField;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Concrete\Package\BasicTablePackage\Src\FieldTypes\DateField;
use Concrete\Package\BasicTablePackage\Src\BaseEntity;

/*because of the hack with @DiscriminatorEntry Annotation, all Doctrine Annotations need to be
properly imported*/
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Concrete\Package\BasicTablePackage\Src\DiscriminatorEntry\DiscriminatorEntry;
use Doctrine\ORM\Mapping\Table;


/**
 * Class EmailAddress
 * package Concrete\Package\BaclucPersonPackage\Src
 * @Entity
 * @Table(name="bacluc_email_address")
 * @DiscriminatorEntry( value = "Concrete\Package\BaclucPersonPackage\Src\EmailAddress" )
 */
class EmailAddress extends Address
{
    use EntityGetterSetter;
    /**
     * @var int
     * @Id @Column(type="integer")
     * @GEneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     * @var string
     * @Column(type="string")
     */
    protected $email;







    public function __construct(){
        parent::__construct();
        if($this->People == null){
            $this->People = new ArrayCollection();
        }

    }

    public function setDefaultFieldTypes()
    {
        parent::setDefaultFieldTypes(); // TODO: Change the autogenerated stub
        $this->fieldTypes['email'] = new EmailField('email', 'Email Address','postemail');

    }

    public static function getDefaultGetDisplayStringFunction(){
        $function = function(EmailAddress $item){

            $returnString ="";
            if(strlen($item->email!=null)){
                $returnString.=$item->email;
            }
            return $returnString;
        };
        return $function;
    }





}